apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/your-cluster
  prune: true
  validation: client
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  url: git@github.com:arch-hcra/p_test_git_flux.git
  ref:
    branch: main
  secretRef:
    name: github-ssh-key
